### ISSUE TITLE
Fatal Issue detected: Error running 'Fawkes-0.3.exe'

### ISSUE THREAD

**Issue by twistios** [Shawn-Shan/fawkes#78] opened 2020-08-26 21:37 UTC
I just downloaded the Fawkes-Software (as of how I understand it, is the GUI-App).

When I run the exe, I get the following error-window:
![fatal error running Fawkes-0_3_exe](https://user-images.githubusercontent.com/54811436/91359475-e815ca00-e7f4-11ea-9bf4-088a0575e5e3.png)

I am using Windows 10.

**Comment by nottheend** [comment] 2020-09-20 23:30
Can also confirm this on Windows 10.
Any Qt framework needed to install?

**Comment by camAtGitHub** [comment] 2021-01-21 23:04
Same issue here with 0.30 and 0.31 Windows installers.
Issue persists with or without Run as Administrator.

Edition	Windows 10 Pro (64bit)
Version	20H2
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by nottheend** [comment] 2021-01-22 14:30
This issue seems to be a duplicate of #93
Or vice versa

**Comment by twistios** [comment] 2021-01-24 21:16
@nottheend as you can see this is #78, while #93 is newer. So #93 is the duplicate.

**Comment by nottheend** [comment] 2021-01-24 21:41
That make sense @twistios. So maybe collaborator would close #93 in favor of #78 then. Maybe @emilywenger could do that?

**Comment by panderlad** [comment] 2021-02-03 17:43
Same here.

Windows 7 64x

So it's not about the windows version.

Tried to install inside a Virtual Machine, Windows 7 64x, AND THE SAME!

This problem persist since August 2020, and no solution yet?

I also tried the binary software, but there some errors on processing.

So can't use it at all.

**Comment by Shawn-Shan** [comment] 2021-02-11 00:56
Can any of you guys try the binary version? If it has error, would you paste the error message here?

**Comment by camAtGitHub** [comment] 2021-02-11 01:58
Hello
I tried:

Name: Fawkes-0.3.1.exe
Size: 131078861 bytes (125 MiB)
SHA1: BDD69DFAA520DE414651F23F0003D4EC92872974

I still get the same error:

Fatal error detected
Failed to execute script app_qt

Thanks

**Comment by maamas29** [comment] 2021-02-11 07:50
same error.
binary version message:

> PS C:\Users\M\Downloads> ./protection-v0.3 -d C:\Users\M\Downloads\New folder
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protection.py", line 13, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 28, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[9464] Failed to execute script protection

**Comment by xirkus** [comment] 2021-04-12 22:04
No installation required: https://dev.scrb.ai

**Comment by Shawn-Shan** [comment] 2021-04-30 15:21
Please try our newest v1.0 release on our website.

**Closed by Shawn-Shan** 2021-04-30 15:21 UTC
